### ISSUE TITLE
Make Split It Favicon

### ISSUE THREAD

**Issue by elliothimmelfarb** [elliothimmelfarb/truffle-split-it#23]
Current favicon is related to the truffle box:
<img width="102" alt="screen shot 2018-03-11 at 4 06 04 pm" src="https://user-images.githubusercontent.com/11192126/37259012-2e95f582-2546-11e8-8997-aea427d9229b.png">
It lives at `public/favicon.ico`

**Comment by kevinhealy** [comment]
![favicon](https://user-images.githubusercontent.com/6722070/37264335-082d787e-256a-11e8-9365-86fae8733791.png)

<img width="101" alt="screen shot 2018-03-11 at 8 24 03 pm" src="https://user-images.githubusercontent.com/6722070/37264356-2cbf298a-256a-11e8-8748-2c62f3df85ad.png">

**Comment by kevinhealy** [comment]
This is a filler for now.  I might change it.
