### ISSUE TITLE
save address input between page changes

### ISSUE THREAD

**Issue by kevinhealy** [elliothimmelfarb/truffle-split-it#31]
Right now, if you have inputed some text and then briefly click on the homepage or view button and then come back all of it is reset.

![input](https://user-images.githubusercontent.com/6722070/37535262-6e796c4e-2904-11e8-8233-5140d384fa38.gif)

It would be nice if it stayed between split-it-page changes.

**Comment by elliothimmelfarb** [comment]
Going to add Redux to the project to make this simpler (so interesting how that works)

**Comment by elliothimmelfarb** [comment]
resolved by #45
