### ISSUE TITLE
Animation library

### ISSUE THREAD

**Issue by kevinhealy** [elliothimmelfarb/truffle-split-it#42]
It would be nice if there was a way to do simple animations for the following UI changes:

(1) the addition of a new row
(2) when the trash cans are added when more than one two rows exist.
(3) perhaps some stuff on the about page

I'm not familiar on animations in react... however, if you know of some simply libraries for this stuff (simple fade in, fade out, transform changes, etc is really all we need) that would be great.

**Comment by elliothimmelfarb** [comment]
Theres a couple of options for this. There are plenty of libraries that do it ([here are a couple](https://www.freshtilledsoil.com/whats-the-most-developer-friendly-react-animation-library/)) but if there are only a few spots that we want to animate we could do it ourselves using [CSS Keyframes](https://css-tricks.com/snippets/css/keyframe-animation-syntax/). Styled components has an [animations section](https://www.styled-components.com/docs/basics#animations) in their docs using Keyframes and [here is a codepen i made a while back](https://codepen.io/elliothimmelfarb/pen/NvQawy) experimenting with keyframes.

**Comment by kevinhealy** [comment]
Great, I was looking at this one too: https://github.com/reactjs/react-transition-group/tree/v1-stable

I found it in the react documentation.  Looks pretty easy.

I'll try and accomplish what I want using it.  You can then see how I get it working, and if there is a more elegant way to accomplish it using keyframes we can do that.

**Comment by elliothimmelfarb** [comment]
Using a library would be the simplest. Thanks for looking for and finding one!
