### ISSUE TITLE
Add button turns gray, but continues to work, if you press it after 10 rows.

### ISSUE THREAD

**Issue by kevinhealy** [elliothimmelfarb/truffle-split-it#46]

**Comment by kevinhealy** [comment]
I found the location of the problem of this... but haven't implemented a solution.

The prop on the addButton named "disabled" is just used for styling... 

In the old version what would happen is before you'd add an address it would check the condition again: if addresses is > 9.

If so it would return...

I suppose a solution would be to just have that check again... this time in the reducer under ADD_ADDRESS.

**Comment by elliothimmelfarb** [comment]
That sounds like the solution
