### ISSUE TITLE
If you delete a row, the 'isDark' background gets messed up

### ISSUE THREAD

**Issue by kevinhealy** [elliothimmelfarb/truffle-split-it#47]
I think all of the rows need to be rerendered when a row is deleted (or at least all the rows after the one that was deleted).  Right now if you have a [gray] [light gray] [gray] pattern and you delete the [light gray] it is [gray] [gray] instead of [gray] [light gray].

**Comment by kevinhealy** [comment]
I resolved this in the post-redux-restorations branch.

In the componentShouldRender method, I added the condition that it looks for changes in isDark

**Comment by elliothimmelfarb** [comment]
Well done!
